package com.kelleci.petsocial.presentation.register

object RegisterConstant {
    val petGenius = listOf("Kedi", "Köpek")
    val petSpay = listOf("Evet", "Hayır")

    val catGeniusList = listOf(
        "Abyssinian",
        "American Bobtail",
        "American Curl",
        "American Shorthair",
        "American Wirehair",
        "Balinese",
        "Bengal",
        "Birman",
        "Bombay",
        "British Shorthair",
        "Burmese",
        "Burmilla",
        "Chartreux",
        "Cornish Rex",
        "Devon Rex",
        "Egyptian Mau",
        "Exotic Shorthair",
        "Havana Brown",
        "Himalayan",
        "Japanese Bobtail",
        "Javanese",
        "Korat",
        "LaPerm",
        "Maine Coon",
        "Manx",
        "Norwegian Forest",
        "Ocicat",
        "Oriental",
        "Persian",
        "Peterbald",
        "Pixiebob",
        "Ragdoll",
        "Russian Blue",
        "Savannah",
        "Scottish Fold",
        "Selkirk Rex",
        "Siamese",
        "Siberian",
        "Singapura",
        "Snowshoe",
        "Somali",
        "Sphynx",
        "Tonkinese",
        "Turkish Angora",
        "Turkish Van"
    )
    val dogGeniusList = listOf(
        "Affenpinscher",
        "Afghan Hound",
        "Airedale Terrier",
        "Akita",
        "Alaskan Malamute",
        "American Bulldog",
        "American Eskimo Dog",
        "American Pit Bull Terrier",
        "American Staffordshire Terrier",
        "American Water Spaniel",
        "Anatolian Shepherd Dog",
        "Australian Cattle Dog",
        "Australian Shepherd",
        "Australian Terrier",
        "Basenji",
        "Basset Hound",
        "Beagle",
        "Bearded Collie",
        "Beauceron",
        "Bedlington Terrier",
        "Belgian Malinois",
        "Belgian Sheepdog",
        "Belgian Tervuren",
        "Bernese Mountain Dog",
        "Bichon Frise",
        "Black and Tan Coonhound",
        "Bloodhound",
        "Border Collie",
        "Border Terrier",
        "Borzoi",
        "Boston Terrier",
        "Bouvier des Flandres",
        "Boxer",
        "Boykin Spaniel",
        "Briard",
        "Brittany",
        "Brussels Griffon",
        "Bull Terrier",
        "Bulldog",
        "Bullmastiff",
        "Cairn Terrier",
        "Canaan Dog",
        "Cane Corso",
        "Cardigan Welsh Corgi",
        "Cavalier King Charles Spaniel",
        "Chesapeake Bay Retriever",
        "Chihuahua",
        "Chinese Crested",
        "Chinese Shar-Pei",
        "Chow Chow",
        "Clumber Spaniel",
        "Cocker Spaniel",
        "Collie",
        "Curly-Coated Retriever",
        "Dachshund",
        "Dalmatian",
        "Dandie Dinmont Terrier",
        "Doberman Pinscher",
        "Dogue de Bordeaux",
        "English Bulldog",
        "English Cocker Spaniel",
        "English Setter",
        "English Springer Spaniel",
        "English Toy Spaniel",
        "Field Spaniel",
        "Finnish Spitz",
        "Flat-Coated Retriever",
        "French Bulldog",
        "German Pinscher",
        "German Shepherd",
        "German Shorthaired Pointer",
        "German Wirehaired Pointer",
        "Giant Schnauzer",
        "Glen of Imaal Terrier",
        "Golden Retriever",
        "Gordon Setter",
        "Great Dane",
        "Great Pyrenees",
        "Greater Swiss Mountain Dog",
        "Greyhound",
        "Harrier",
        "Havanese",
        "Irish Setter",
        "Irish Terrier",
        "Irish Water Spaniel",
        "Irish Wolfhound",
        "Italian Greyhound",
        "Jack Russell Terrier",
        "Japanese Chin",
        "Keeshond",
        "Kerry Blue Terrier",
        "Komondor",
        "Kuvasz",
        "Labrador Retriever",
        "Lakeland Terrier",
        "Lhasa Apso",
        "Lowchen",
        "Maltese",
        "Manchester Terrier",
        "Mastiff",
        "Miniature Pinscher",
        "Miniature Schnauzer",
        "Neapolitan Mastiff",
        "Newfoundland",
        "Norfolk Terrier",
        "Norwegian Elkhound",
        "Norwich Terrier",
        "Nova Scotia Duck Tolling Retriever",
        "Old English Sheepdog",
        "Otterhound",
        "Papillon",
        "Pekingese",
        "Pembroke Welsh Corgi",
        "Petit Basset Griffon Vendeen",
        "Pharaoh Hound",
        "Plott",
        "Pointer",
        "Polish Lowland Sheepdog",
        "Pomeranian",
        "Poodle",
        "Portuguese Water Dog",
        "Pug",
        "Puli",
        "Pumi",
        "Redbone Coonhound",
        "Rhodesian Ridgeback",
        "Rottweiler",
        "Saint Bernard",
        "Saluki",
        "Samoyed",
        "Schipperke",
        "Scottish Deerhound",
        "Scottish Terrier",
        "Sealyham Terrier",
        "Shetland Sheepdog",
        "Shiba Inu",
        "Shih Tzu",
        "Siberian Husky",
        "Silky Terrier",
        "Skye Terrier",
        "Soft Coated Wheaten Terrier",
        "Spinone Italiano",
        "Staffordshire Bull Terrier",
        "Standard Schnauzer",
        "Sussex Spaniel",
        "Tibetan Mastiff",
        "Tibetan Spaniel",
        "Tibetan Terrier",
        "Toy Fox Terrier",
        "Vizsla",
        "Weimaraner",
        "Welsh Springer Spaniel",
        "Welsh Terrier",
        "West Highland White Terrier",
        "Whippet",
        "Wirehaired Pointing Griffon",
        "Yorkshire Terrier"
    )


}